#!bash
## ipad_rsa is expected to be here in this dir
set -e

mkdir ~/.ssh && curl -fsL https://github.com/latbauerdick.keys > ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
mv $(pwd)/ipad_rsa ~/.ssh/id_rsa
chmod 0600 ~/.ssh/id_rsa

git clone --recursive git@github.com:latbauerdick/dotfiles ~/.dotfiles \
    && ln -sf ~/.dotfiles/vim/init.vim ~/.vimrc         \
    && mkdir -p ~/.config                               \
    && ln -sf ~/.dotfiles/vim ~/.config/nvim            \
    && ln -sf $(pwd)/.dotfiles/zsh/zshrc ~/.zshrc                 \
    && ln -sf $(pwd)/.dotfiles/tmux/tmux.conf.nix ~/.tmux.conf \
    && ln -sf $(pwd)/.dotfiles/git/gitconfig ~/.gitconfig         \
    && ln -sf $(pwd)/.dotfiles/ssh/sshconfig ~/.ssh/config        \
    && ln -sf $(pwd)/.dotfiles/nixpkgs ~/.config/

git clone git@github.com:robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
git clone git@github.com:bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

nix-env -iA nixos.python36Packages.powerline
echo -e "with import <nixpkgs> {};\npython.withPackages (ps: with ps; [ powerline ])" > build.nix
nix-env -f build.nix -i && python -c 'import powerline; print (powerline.__file__)'
rm build.nix


nix-env -iA myPackages -f '<nixpkgs>'

echo source $(python -c 'import powerline; print (powerline.__file__)')/bindings/tmux/powerline.conf

