#!bash
## ipad_rsa is expected to be here in this dir
set -e

# get keys from github
mkdir ~/.ssh && curl -fsL https://github.com/latbauerdick.keys > ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
mv $(pwd)/ipad_rsa ~/.ssh/id_rsa
chmod 0600 ~/.ssh/id_rsa

# link dotfiles to where they're needed
git clone --recursive git@gitlab.com:latb/dotfiles ~/.dotfiles \
    && ln -sf ~/.dotfiles/vim/init.vim ~/.vimrc         \
    && mkdir -p ~/.config                               \
    && ln -sf ~/.dotfiles/vim ~/.config/nvim            \
    && ln -sf $(pwd)/.dotfiles/zsh/zshrc ~/.zshrc                 \
    && ln -sf $(pwd)/.dotfiles/tmux/tmux.conf ~/.tmux.conf \
    && ln -sf $(pwd)/.dotfiles/git/gitconfig ~/.gitconfig         \
    && ln -sf $(pwd)/.dotfiles/ssh/sshconfig ~/.ssh/config        \
    && ln -sf $(pwd)/.dotfiles/nixpkgs ~/.config/

# oh-my-zsh and powerlevel9k theme
git clone git@github.com:robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
git clone git@github.com:bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

# powerline
# nix-env -iA nixos.python36Packages.powerline
pip3 install powerline-status
pip3 install --user psutil

