# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Nix

[ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]
  && . $HOME/.nix-profile/etc/profile.d/nix.sh

[ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]
  && . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'

[ -e $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh ] 
  && . $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh

# End Nix


# vi mode
bindkey -v

# oh-my-zsh {{{
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
ZSH_THEME=powerlevel10k/powerlevel10k
DEFAULT_USER="bauerdic"
plugins=(git z history history-substring-search)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8


# }}}

# Alias' {{{
alias vi="vim"

### LATB mods
alias zl="zfs list -t all -r -o name,used,refer"

alias exifHel=exiftool -FocalLength=58 -MinFocalLength=58 -MaxFocalLength=58 -FocalLengthIn35mmFormat=87 -LensInfo="58 58 2.0 2.0" -LensMake="Helios" -LensModel="Helios 44M-4 58mm f/2" -LensSerialNumber=87006073
alias exif135=exiftool -FocalLength=135 -MinFocalLength=135 -MaxFocalLength=135 -FocalLengthIn35mmFormat=203 -LensInfo="135 135 2.8 2.8" -LensMake="Minolta" -LensModel="MD Tele Rokkor-X 135mm f/2.8" -LensSerialNumber=1232686

LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R -X -F '

export BAT_THEME="Solarized (light)"

# kitty terminal emulator extensions
# most won't work with tmux
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"

# setup root6
#pushd $(brew --prefix root6) >/dev/null; . libexec/thisroot.sh; popd >/dev/null

# }}}
# i

# Exports {{{
export GITHUB_USER="latbauerdick"
export PATH=~/bin:~/.local/bin:~/.npm-global/bin:/usr/local/sbin:/usr/local/bin:$PATH:~/Library/Python/3.9/bin

# export GREP_OPTIONS='--color=auto'
export MANPAGER="less -X -i" # Don’t clear the screen after quitting a manual page
# export CLICOLOR=1
#export LSCOLORS=Gxfxcxdxbxegedabagacad
#export LS_COLORS=Gxfxcxdxbxegedabagacad
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'
#
### LATB exports
export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

# }}}
#
# Convert simplified wildcard pattern to regex and grep a file listing using
# Silver Searcher (`brew install the_silver_searcher`)
lsgrep ()
{
    NEEDLE="$(echo $@|sed -E 's/\.([a-z0-9]+)$/\\.\1/'|sed -E 's/\?/./'| sed -E 's/[ *]/.*?/g')";
    ag --depth 3 -S -g "$NEEDLE" 2> /dev/null
  }

alias l='ls -alh'

alias stss="(sleep 4; open vnc://127.0.0.1:5901) & ssh -C -4 -L 5901:127.0.0.1:5900"
alias imac='sshpass -e ssh imac'  # put passwd into env SSHPASS

alias dls="docker images"
alias dps="docker ps -a"
alias drm="docker rm"
alias drmi="docker rmi"
alias dri="docker run -it --privileged -v /Volumes/Data:/Volumes/Data"
alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder'

alias gs='git status '
alias ga='git add '
alias gaa='git add -A '
alias gb='git branch '
alias gc='git commit '
alias gcm='git commit -m '
alias go='git checkout '

alias n="neuron -d ~/zk"
alias nn="neuron -d ~/zk new -e"
alias ns="neuron -d ~/zk search"
alias na="neuron -d ~/zk search -a"
alias xo='xargs -I % open %'
alias xe='xargs -I % $EDITOR %'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

alias nv='nvim'
export EDITOR="nvim"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files'

eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f "/home/bauerdic/.ghcup/env" ] && source "/home/bauerdic/.ghcup/env" # ghcup-env

export BAT_THEME="Solarized (light)"

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="/usr/local/opt/arm-gcc-bin@8/bin:$PATH"
autoload -U zmv

