#!bash

set -e

ln -sf $(pwd)/id_rsa ~/.ssh/
chmod 0600 ~/.ssh/id_rsa

cd ~/.dotfiles
git remote set-url origin git@github.com:latbauerdick/dotfiles

nix-env -iA myPackages -f '<nixpkgs>'

####. $HOME/.nix-profile/etc/profile.d/nix.sh
####export LOCALE_ARCHIVE=`nix-env --installed --no-name --out-path --query glibc-locales`/lib/locale/locale-archive
####export LANG=en_US.UTF-8
####export LC_ALL=en_US.UTF-8

echo source $(python -c 'import powerline; print (powerline.__file__)')/bindings/tmux/powerline.conf
